# Generated by Django 4.2.10 on 2024-02-26 13:28

from django.db import migrations, models
import shortner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_shorturlmodel_delete_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_code',
            field=models.CharField(default=shortner.models.generate_short_code, max_length=12, unique=True),
        ),
    ]
